name: Test, Build and Deploy PHP App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: php-actions/composer@v6
      with:
        php_version: '8.2'

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v4
      with:
        php_version: '8.2'
        args: tests
        bootstrap: vendor/autoload.php
  deployment:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deployment on Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd /home/ps_project/clinic-appointment-system/src

            # Najnowsze zmiany zostają pobrane na dysk maszyny wirtualnej
            git pull origin main
