name: Test, Build and Deploy PHP App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: php-actions/composer@v6
      with:
        php_version: '8.2'

    - name: PHPUnit Tests
      uses: php-actions/phpunit@v4
      with:
        php_version: '8.2'
        args: tests
        bootstrap: vendor/autoload.php
